# Project: POKEMON
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o src/Battle/BattleManager.o src/Battle/WildEncounterManager.o src/Character/Player/Player.o src/Character/ProfessorOak.o src/Main/Game.o src/Pokemon/Pokemon.o src/Utility/Utility.o
LINKOBJ  = main.o src/Battle/BattleManager.o src/Battle/WildEncounterManager.o src/Character/Player/Player.o src/Character/ProfessorOak.o src/Main/Game.o src/Pokemon/Pokemon.o src/Utility/Utility.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = POKEMON.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

src/Battle/BattleManager.o: src/Battle/BattleManager.cpp
	$(CPP) -c src/Battle/BattleManager.cpp -o src/Battle/BattleManager.o $(CXXFLAGS)

src/Battle/WildEncounterManager.o: src/Battle/WildEncounterManager.cpp
	$(CPP) -c src/Battle/WildEncounterManager.cpp -o src/Battle/WildEncounterManager.o $(CXXFLAGS)

src/Character/Player/Player.o: src/Character/Player/Player.cpp
	$(CPP) -c src/Character/Player/Player.cpp -o src/Character/Player/Player.o $(CXXFLAGS)

src/Character/ProfessorOak.o: src/Character/ProfessorOak.cpp
	$(CPP) -c src/Character/ProfessorOak.cpp -o src/Character/ProfessorOak.o $(CXXFLAGS)

src/Main/Game.o: src/Main/Game.cpp
	$(CPP) -c src/Main/Game.cpp -o src/Main/Game.o $(CXXFLAGS)

src/Pokemon/Pokemon.o: src/Pokemon/Pokemon.cpp
	$(CPP) -c src/Pokemon/Pokemon.cpp -o src/Pokemon/Pokemon.o $(CXXFLAGS)

src/Utility/Utility.o: src/Utility/Utility.cpp
	$(CPP) -c src/Utility/Utility.cpp -o src/Utility/Utility.o $(CXXFLAGS)
